version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.3.7
        environment:
          MONGODB_URL: mongo
          RACK_ENV: test
          REDIS_URL: 'redis://localhost:6379'
          COVERAGE: 'true'
      - image: mongo:3.2
      - image: redis:3.2
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: coverage
